"""add agent run error column

Revision ID: 2b557369a291
Revises: dc3ced607182
Create Date: 2026-09-08 04:27:05.195881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2b557369a291'
down_revision: Union[str, None] = 'dc3ced607182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'error')
    # ### end Alembic commands ###
