"""add decisions

Revision ID: 6aa9bbd0eb67
Revises: 73c37e6f9104
Create Date: 2026-09-08 01:54:17.193697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6aa9bbd0eb67'
down_revision: Union[str, None] = '73c37e6f9104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decisions',
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('conclusion', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.Column('recommended_actions', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_organization_id'), 'decisions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_decisions_run_id'), 'decisions', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_run_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_organization_id'), table_name='decisions')
    op.drop_table('decisions')
    # ### end Alembic commands ###
